import * as Icons from "components/icons.list";
import { DatePicker, Input, Select } from "antd";
import YesNoFieldType from "./field types/YesNoFieldType";
import StartRatingFieldType from "./field types/StarRatingFieldType";
import CheckboxFieldType from "./field types/CheckboxFieldType";
import EmailInput from "./field types/EmailInput";
import {
  checkbox_validations,
  currency_type_validations,
  date_input_validations,
  date_time_input_validations,
  drop_down_input_validations,
  multi_select_validations,
  number_input_validations,
  text_area_validation,
  text_field_validation,
  yes_no_input_validations,
  email_type_validations,
  attachment_type_validations,
} from "./validationsInputFieldsList";
import AttachmentFieldType from "./field types/AttachmentFieldType";
import RichTextFieldType from "./field types/RichTextFieldType";
import SelectPlaceHolder from "./field types/SelectPlaceHolder";

const inputFieldsList = [
  {
    name: "Label",
    icon: Icons.TextAreaIcon,
    component: RichTextFieldType,
    id: "rich_text_area",
    inputProps: {},
    options: ["field_type", "rich_text_default"],
    validations: [],
    hideNameAndHelpText: true,
  },
  {
    name: "Text",
    icon: Icons.TextFieldIcon,
    component: Input,
    id: "text_field_type",
    inputProps: {},
    options: [
      "name",
      "field_type",
      "required",
      "field_id",
      "help_text",
      "mask_input_schema",
      "default_value_mask",
    ],
    validations: text_field_validation,
    hideNameAndHelpText: false,
  },
  {
    name: "Text area",
    icon: Icons.TextAreaIcon,
    component: Input.TextArea,
    id: "text_area_type",
    inputProps: {},
    options: ["name", "field_type", "required", "field_id", "help_text"],
    validations: text_area_validation,
    hideNameAndHelpText: false,
  },
  {
    name: "Number",
    icon: Icons.TextFieldNumberIcon,
    component: Input,
    id: "number_input_type",
    inputProps: {},
    options: [
      "name",
      "field_type",
      "required",
      "field_id",
      "help_text",
      "mask_input_schema",
      "default_value_mask",
      "decimal_places",
    ],
    validations: number_input_validations,
    hideNameAndHelpText: false,
  },
  {
    name: "Date",
    icon: Icons.DatePickerIcon,
    component: DatePicker,
    id: "date_input_type",
    inputProps: {
      className: "w-full",
      placeholder: "YYYY-MM-DD",
    },
    options: [
      "name",
      "field_type",
      "required",
      "field_id",
      "help_text",
      "default_value_date",
    ],
    validations: date_input_validations,
    hideNameAndHelpText: false,
  },
  {
    name: "Date & Time",
    icon: Icons.DateAndTimeIcon,
    component: DatePicker,
    id: "date_time_input_type",
    inputProps: {
      showTime: { format: "hh:mm A" },
      className: "w-full",
      placeholder: "YYYY-MM-DD HH:MM",
      format: "YYYY-MM-DD hh:mm A",
    },
    options: [
      "name",
      "field_type",
      "required",
      "field_id",
      "help_text",
      "default_value_date_time",
    ],
    validations: date_time_input_validations,
    hideNameAndHelpText: false,
  },
  {
    name: "Dropdown",
    icon: Icons.DropDownIcon,
    component: SelectPlaceHolder,
    id: "drop_down_input_type",
    inputProps: {},
    options: [
      "name",
      "field_type",
      "required",
      "field_id",
      "help_text",
      "select_list",
      "default_value_select",
      "dependent_list",
    ],
    validations: drop_down_input_validations,
    hideNameAndHelpText: false,
  },
  {
    name: "Yes/No",
    icon: Icons.ToggleIcon,
    component: YesNoFieldType,
    id: "yes_no_type",
    inputProps: {},
    options: [
      "name",
      "field_type",
      "field_id",
      "help_text",
      "default_value_yes_no",
    ],
    validations: yes_no_input_validations,
    hideNameAndHelpText: false,
  },
  {
    name: "Multi-select dropdown",
    icon: Icons.MultiSelectIcon,
    component: SelectPlaceHolder,
    id: "multi_select_type",
    inputProps: {},
    options: [
      "name",
      "field_type",
      "required",
      "field_id",
      "help_text",
      "select_list",
      "default_value_multiple_select",
      "dependent_list",
    ],
    validations: multi_select_validations,
    hideNameAndHelpText: false,
  },
  {
    name: "Checkbox",
    icon: Icons.CheckboxIcon,
    component: CheckboxFieldType,
    id: "checkbox_type",
    inputProps: {},
    options: [
      "name",
      "field_type",
      "field_id",
      "required",
      "help_text",
      "select_list",
      "default_value_check_box",
    ],
    validations: checkbox_validations,
    hideNameAndHelpText: false,
  },
  {
    name: "Currency",
    icon: Icons.CurrencyIcon,
    component: Input,
    id: "currency_type",
    inputProps: {
      addonAfter: "USD",
      placeholder: "$",
    },
    options: [
      "name",
      "field_type",
      "field_id",
      "required",
      "help_text",
      "accepted_currencies",
      "default_value",
      "decimal_places",
    ],
    validations: currency_type_validations,
    hideNameAndHelpText: false,
  },
  {
    name: "Email",
    icon: Icons.EmailIcon,
    component: EmailInput,
    id: "email_type",
    inputProps: {},
    options: [
      "name",
      "field_type",
      "required",
      "field_id",
      "help_text",
      "default_value",
    ],
    validations: email_type_validations,
    hideNameAndHelpText: false,
  },
  {
    name: "Rating",
    icon: Icons.RatingIcon,
    component: StartRatingFieldType,
    id: "rating_type",
    inputProps: {},
    options: [
      "name",
      "field_type",
      "field_id",
      "required",
      "help_text",
      "default_value_star_rating",
    ],
    validations: [],
    hideNameAndHelpText: false,
  },
  {
    name: "Attachment",
    icon: Icons.AttachmentIcon,
    component: AttachmentFieldType,
    id: "attachment_type",
    inputProps: {},
    options: [
      "name",
      "field_type",
      "field_id",
      "required",
      "help_text",
      "allowed_file_types",
      "max_file_size",
    ],
    validations: attachment_type_validations,
    hideNameAndHelpText: false,
  },
];

export default inputFieldsList;
